-- ============================================================
-- BETA SCENARIO PART 5: Tickets (14 tickets + 8 sub-tickets)
-- ============================================================
-- NOTE: sequence_number is auto-generated by trigger.
-- We explicitly set it here for seeding with service role.
-- ============================================================

BEGIN;

-- ============================================================
-- PROJECT 1 TICKETS (3 tickets, completed)
-- ============================================================

-- Ticket 1: Design and implement staggered shift schedule
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES (
  'aa010000-0000-4000-8000-000000000001',
  'b0010000-0000-4000-8000-000000000001',
  1,
  'f0010000-0000-4000-8000-000000000001',
  'Design and implement staggered shift schedule',
  'Based on the demand curve analysis, design a 3-shift model (Early 6am-2pm, Core 9am-5pm, Late 1pm-9pm) and work with HR to implement. Must account for agent preferences and shift differential pay.',
  'task', 'done', 'critical',
  'implement',
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'c0010000-0000-4000-8000-000000000001', -- Sarah
  'd0010000-0000-4000-8000-000000000001',
  '2026-02-17',
  '2026-02-10 09:00:00+00',
  '2026-02-17 14:00:00+00',
  ARRAY['scheduling', 'hr', 'critical-path'],
  '2026-02-07 10:00:00+00'
);

-- Sub-tickets for Ticket 1
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, parent_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES
(
  'aa010000-0000-4000-8000-000000000011',
  'b0010000-0000-4000-8000-000000000001',
  2,
  'f0010000-0000-4000-8000-000000000001',
  'aa010000-0000-4000-8000-000000000001',
  'Pull 90-day hourly ticket volume data from Zendesk API',
  'Export ticket creation timestamps for the past 90 days and create hourly volume chart to identify peak patterns.',
  'task', 'done', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000006', -- James
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'd0010000-0000-4000-8000-000000000003',
  '2026-02-12',
  '2026-02-10 10:00:00+00',
  '2026-02-12 11:00:00+00',
  ARRAY['data', 'zendesk'],
  '2026-02-10 09:00:00+00'
),
(
  'aa010000-0000-4000-8000-000000000012',
  'b0010000-0000-4000-8000-000000000001',
  3,
  'f0010000-0000-4000-8000-000000000001',
  'aa010000-0000-4000-8000-000000000001',
  'Get HR fast-track approval for new shift structure',
  'Sarah to coordinate with CHRO to bypass normal 2-week approval process. Need approval by Feb 17 for rollout.',
  'task', 'done', 'critical',
  'implement',
  'c0010000-0000-4000-8000-000000000001', -- Sarah
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'd0010000-0000-4000-8000-000000000001',
  '2026-02-14',
  '2026-02-12 09:00:00+00',
  '2026-02-14 16:00:00+00',
  ARRAY['hr', 'approval'],
  '2026-02-10 09:00:00+00'
),
(
  'aa010000-0000-4000-8000-000000000013',
  'b0010000-0000-4000-8000-000000000001',
  4,
  'f0010000-0000-4000-8000-000000000001',
  'aa010000-0000-4000-8000-000000000001',
  'Survey agents for shift preferences',
  'Send preference survey to all 14 agents. Options: Early (6-2), Core (9-5), Late (1-9). First come first served for preferences, then assign remaining.',
  'task', 'done', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'd0010000-0000-4000-8000-000000000001',
  '2026-02-14',
  '2026-02-12 10:00:00+00',
  '2026-02-13 17:00:00+00',
  ARRAY['communication', 'survey'],
  '2026-02-10 09:00:00+00'
);

-- Ticket 2: Configure Zendesk priority queues
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES (
  'aa010000-0000-4000-8000-000000000002',
  'b0010000-0000-4000-8000-000000000001',
  5,
  'f0010000-0000-4000-8000-000000000001',
  'Configure Zendesk priority queues (Enterprise/Paid/Free)',
  'Create 3 separate queues in Zendesk with auto-routing based on customer tier. Configure SLA timers: Enterprise 15min, Paid 30min, Free 2hr. Set up SLA breach alerts to Slack #support-alerts channel.',
  'task', 'done', 'critical',
  'implement',
  'c0010000-0000-4000-8000-000000000003', -- Aisha
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'd0010000-0000-4000-8000-000000000001',
  '2026-02-24',
  '2026-02-17 09:00:00+00',
  '2026-02-24 15:00:00+00',
  ARRAY['zendesk', 'configuration', 'sla'],
  '2026-02-14 09:00:00+00'
);

-- Sub-tickets for Ticket 2
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, parent_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES
(
  'aa010000-0000-4000-8000-000000000021',
  'b0010000-0000-4000-8000-000000000001',
  6,
  'f0010000-0000-4000-8000-000000000001',
  'aa010000-0000-4000-8000-000000000002',
  'Set up Slack webhook for SLA breach alerts',
  'Create Zendesk trigger -> Slack webhook integration. Alert #support-alerts when any ticket approaches SLA breach (80% of timer).',
  'task', 'done', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000006', -- James
  'c0010000-0000-4000-8000-000000000003', -- Aisha
  'd0010000-0000-4000-8000-000000000003',
  '2026-02-19',
  '2026-02-17 10:00:00+00',
  '2026-02-19 14:00:00+00',
  ARRAY['slack', 'webhook', 'alerts'],
  '2026-02-17 09:00:00+00'
);

-- Ticket 3: Monitor and report post-deployment metrics
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES (
  'aa010000-0000-4000-8000-000000000003',
  'b0010000-0000-4000-8000-000000000001',
  7,
  'f0010000-0000-4000-8000-000000000001',
  'Monitor and produce before/after evaluation report',
  'Track daily response time metrics for 2 weeks post-deployment. Produce before/after comparison for Step 6 evaluation. Include CSAT trend, SLA compliance, and agent satisfaction.',
  'task', 'done', 'high',
  'evaluate',
  'c0010000-0000-4000-8000-000000000006', -- James
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'd0010000-0000-4000-8000-000000000003',
  '2026-03-05',
  '2026-02-17 09:00:00+00',
  '2026-03-05 15:00:00+00',
  ARRAY['metrics', 'evaluation', 'reporting'],
  '2026-02-17 09:00:00+00'
);

-- ============================================================
-- PROJECT 2 TICKETS (3 tickets, mix of done and in progress)
-- ============================================================

-- Ticket 4: Define ticket categorization taxonomy
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES (
  'aa020000-0000-4000-8000-000000000001',
  'b0010000-0000-4000-8000-000000000001',
  8,
  'f0010000-0000-4000-8000-000000000002',
  'Define ticket categorization taxonomy (20 categories, 3 levels)',
  'Audit existing 55 ad-hoc tags and consolidate into a structured 3-level taxonomy. Get approval from support team. Create mapping document from old tags to new categories.',
  'task', 'done', 'critical',
  'implement',
  'c0010000-0000-4000-8000-000000000002', -- Marcus
  'c0010000-0000-4000-8000-000000000004', -- David
  'd0010000-0000-4000-8000-000000000001',
  '2026-02-21',
  '2026-02-17 09:00:00+00',
  '2026-02-21 16:00:00+00',
  ARRAY['taxonomy', 'categorization'],
  '2026-02-14 10:00:00+00'
);

-- Ticket 5: Build and deploy rule-based classifier
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES (
  'aa020000-0000-4000-8000-000000000002',
  'b0010000-0000-4000-8000-000000000001',
  9,
  'f0010000-0000-4000-8000-000000000002',
  'Build and deploy rule-based ticket classifier',
  'Create Python service that classifies tickets using keyword matching + regex patterns against the new taxonomy. Deploy to staging. Target: >75% accuracy before ML enhancement.',
  'task', 'done', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000005', -- Priya
  'c0010000-0000-4000-8000-000000000004', -- David
  'd0010000-0000-4000-8000-000000000002',
  '2026-02-28',
  '2026-02-21 09:00:00+00',
  '2026-02-27 17:00:00+00',
  ARRAY['classifier', 'python', 'rules'],
  '2026-02-17 10:00:00+00'
);

-- Ticket 6: Train ML model and integrate as fallback (IN PROGRESS)
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at,
  tags, created_at
) VALUES (
  'aa020000-0000-4000-8000-000000000003',
  'b0010000-0000-4000-8000-000000000001',
  10,
  'f0010000-0000-4000-8000-000000000002',
  'Train ML classification model and integrate as fallback router',
  'Using 10K labeled historical tickets, train scikit-learn classifier. Deploy as FastAPI microservice. Integrate with confidence scoring — route automatically if >80% confident, send to human queue if below. Target: >85% accuracy.',
  'task', 'in_progress', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000005', -- Priya
  'c0010000-0000-4000-8000-000000000004', -- David
  'd0010000-0000-4000-8000-000000000002',
  '2026-03-07',
  '2026-03-01 09:00:00+00',
  ARRAY['ml', 'scikit-learn', 'fastapi'],
  '2026-02-24 10:00:00+00'
);

-- Sub-tickets for Ticket 6
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, parent_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES
(
  'aa020000-0000-4000-8000-000000000031',
  'b0010000-0000-4000-8000-000000000001',
  11,
  'f0010000-0000-4000-8000-000000000002',
  'aa020000-0000-4000-8000-000000000003',
  'Label 10K historical tickets with new taxonomy',
  'Export 10,000 tickets from the past 2 years. Apply new taxonomy labels. Create 80/20 train/test split. Document labeling guidelines for consistency.',
  'task', 'done', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000008', -- Tom
  'c0010000-0000-4000-8000-000000000004', -- David
  'd0010000-0000-4000-8000-000000000002',
  '2026-02-28',
  '2026-02-24 09:00:00+00',
  '2026-03-01 14:00:00+00',
  ARRAY['data-labeling', 'ml-training'],
  '2026-02-24 09:00:00+00'
),
(
  'aa020000-0000-4000-8000-000000000032',
  'b0010000-0000-4000-8000-000000000001',
  12,
  'f0010000-0000-4000-8000-000000000002',
  'aa020000-0000-4000-8000-000000000003',
  'Build confidence scoring + human review queue',
  'Add confidence score to classifier output. Build a human triage queue in Zendesk for tickets below 80% confidence. Track human corrections for model retraining.',
  'task', 'in_progress', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000004', -- David
  'c0010000-0000-4000-8000-000000000004', -- David
  'd0010000-0000-4000-8000-000000000002',
  '2026-03-07',
  '2026-03-03 09:00:00+00',
  NULL,
  ARRAY['confidence-scoring', 'queue'],
  '2026-03-01 09:00:00+00'
);

-- ============================================================
-- PROJECT 3 TICKETS (2 tickets)
-- ============================================================

-- Ticket 7: Evaluate dashboard platforms
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at,
  tags, created_at
) VALUES (
  'aa030000-0000-4000-8000-000000000001',
  'b0010000-0000-4000-8000-000000000001',
  13,
  'f0010000-0000-4000-8000-000000000003',
  'Evaluate dashboard platforms and produce recommendation',
  'Test Grafana, Metabase, custom React, and Datadog against our criteria matrix. Build a proof-of-concept with each showing live queue depth. Present recommendation to team.',
  'task', 'in_progress', 'high',
  'select_plan',
  'c0010000-0000-4000-8000-000000000008', -- Tom
  'c0010000-0000-4000-8000-000000000006', -- James
  'd0010000-0000-4000-8000-000000000002',
  '2026-03-07',
  '2026-02-26 09:00:00+00',
  ARRAY['dashboard', 'evaluation', 'poc'],
  '2026-02-25 10:00:00+00'
);

-- Ticket 8: Set up Zendesk streaming data pipeline
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date,
  tags, created_at
) VALUES (
  'aa030000-0000-4000-8000-000000000002',
  'b0010000-0000-4000-8000-000000000001',
  14,
  'f0010000-0000-4000-8000-000000000003',
  'Set up Zendesk webhook -> streaming data pipeline',
  'Replace nightly batch ETL with real-time webhook pipeline. Zendesk ticket events -> webhook -> queue -> database. Must support <60s data freshness for dashboard.',
  'task', 'todo', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000006', -- James
  'c0010000-0000-4000-8000-000000000006', -- James
  'd0010000-0000-4000-8000-000000000003',
  '2026-03-14',
  ARRAY['data-pipeline', 'streaming', 'zendesk'],
  '2026-02-26 10:00:00+00'
);

-- ============================================================
-- PROJECT 4 TICKETS (2 tickets)
-- ============================================================

-- Ticket 9: Audit and update all 340 KB articles
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at,
  tags, created_at
) VALUES (
  'aa040000-0000-4000-8000-000000000001',
  'b0010000-0000-4000-8000-000000000001',
  15,
  'f0010000-0000-4000-8000-000000000004',
  'Audit all 340 KB articles: update, archive, or rewrite',
  'Review every KB article. Categorize as: Current (keep), Outdated (update), Stale (archive), Missing (create new). Target: 95% current articles within 2 weeks.',
  'task', 'in_progress', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000010', -- Carlos
  'c0010000-0000-4000-8000-000000000010', -- Carlos
  'd0010000-0000-4000-8000-000000000001',
  '2026-03-14',
  '2026-03-03 09:00:00+00',
  ARRAY['kb', 'content-audit'],
  '2026-03-01 10:00:00+00'
);

-- Sub-ticket for Ticket 9
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, parent_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at,
  tags, created_at
) VALUES (
  'aa040000-0000-4000-8000-000000000011',
  'b0010000-0000-4000-8000-000000000001',
  16,
  'f0010000-0000-4000-8000-000000000004',
  'aa040000-0000-4000-8000-000000000001',
  'Rewrite top 20 articles in customer-friendly language',
  'Identify the 20 highest-traffic articles and rewrite using the new customer-facing template. Include screenshots, step-by-step instructions, and common variations.',
  'task', 'in_progress', 'high',
  'implement',
  'c0010000-0000-4000-8000-000000000010', -- Carlos
  'c0010000-0000-4000-8000-000000000010', -- Carlos
  'd0010000-0000-4000-8000-000000000001',
  '2026-03-10',
  '2026-03-05 09:00:00+00',
  ARRAY['kb', 'rewrite', 'customer-facing'],
  '2026-03-03 09:00:00+00'
);

-- Ticket 10: Research AI-powered KB search solutions
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date,
  tags, created_at
) VALUES (
  'aa040000-0000-4000-8000-000000000002',
  'b0010000-0000-4000-8000-000000000001',
  17,
  'f0010000-0000-4000-8000-000000000004',
  'Research and evaluate AI-powered KB search solutions',
  'Evaluate Algolia, Elasticsearch, and Zendesk native search. Test with real customer queries. Produce recommendation with cost comparison.',
  'task', 'todo', 'medium',
  'select_plan',
  'c0010000-0000-4000-8000-000000000005', -- Priya
  'c0010000-0000-4000-8000-000000000010', -- Carlos
  'd0010000-0000-4000-8000-000000000002',
  '2026-03-14',
  ARRAY['search', 'ai', 'evaluation'],
  '2026-03-03 10:00:00+00'
);

-- ============================================================
-- PROJECT 5 TICKETS (2 tickets)
-- ============================================================

-- Ticket 11: Interview senior agents about effective training patterns
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date, started_at,
  tags, created_at
) VALUES (
  'aa050000-0000-4000-8000-000000000001',
  'b0010000-0000-4000-8000-000000000001',
  18,
  'f0010000-0000-4000-8000-000000000005',
  'Interview 4 senior agents about effective training patterns',
  'Conduct structured interviews with Aisha, Rachel, and 2 other senior agents. Focus on: what helped them ramp up, what they wish they had, what they teach new hires, biggest knowledge gaps.',
  'task', 'in_progress', 'medium',
  'analyze',
  'c0010000-0000-4000-8000-000000000007', -- Lisa
  'c0010000-0000-4000-8000-000000000007', -- Lisa
  'd0010000-0000-4000-8000-000000000003',
  '2026-03-10',
  '2026-03-05 09:00:00+00',
  ARRAY['interviews', 'research', 'training'],
  '2026-03-04 10:00:00+00'
);

-- Ticket 12: Benchmark competitor training programs
INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  pips_step, assignee_id, reporter_id, team_id, due_date,
  tags, created_at
) VALUES (
  'aa050000-0000-4000-8000-000000000002',
  'b0010000-0000-4000-8000-000000000001',
  19,
  'f0010000-0000-4000-8000-000000000005',
  'Benchmark industry training programs and certification models',
  'Research how Zendesk, Intercom, Freshdesk, and HubSpot train their support teams. Identify best practices for certification tiers, skill assessments, and ramp timelines.',
  'task', 'todo', 'medium',
  'analyze',
  'c0010000-0000-4000-8000-000000000006', -- James
  'c0010000-0000-4000-8000-000000000007', -- Lisa
  'd0010000-0000-4000-8000-000000000003',
  '2026-03-12',
  ARRAY['benchmarking', 'research', 'industry'],
  '2026-03-04 10:00:00+00'
);

-- ============================================================
-- BUG TICKET (discovered during Project 1 implementation)
-- ============================================================

INSERT INTO tickets (
  id, org_id, sequence_number, project_id, title, description, type, status, priority,
  assignee_id, reporter_id, team_id, due_date, started_at, resolved_at,
  tags, created_at
) VALUES (
  'aa060000-0000-4000-8000-000000000001',
  'b0010000-0000-4000-8000-000000000001',
  20,
  'f0010000-0000-4000-8000-000000000001',
  'BUG: Enterprise tickets sometimes miscategorized as Free tier',
  'When a customer has multiple accounts (free personal + enterprise work), Zendesk sometimes routes based on the personal account tier. Discovered 3 cases in first week of priority queue deployment.',
  'bug', 'done', 'critical',
  'c0010000-0000-4000-8000-000000000003', -- Aisha
  'c0010000-0000-4000-8000-000000000009', -- Rachel (discovered it)
  'd0010000-0000-4000-8000-000000000001',
  '2026-02-26',
  '2026-02-25 10:00:00+00',
  '2026-02-26 14:00:00+00',
  ARRAY['bug', 'zendesk', 'tier-routing'],
  '2026-02-25 10:00:00+00'
);

COMMIT;
