import { createClient } from '@supabase/supabase-js'

/**
 * Server-side test data factories for E2E tests.
 *
 * These create data directly via the Supabase admin client,
 * bypassing the UI for fast, deterministic test setup.
 *
 * Requires env vars:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 */

const getAdminClient = () => {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!url || !key) {
    throw new Error(
      'Test factories require NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars',
    )
  }

  return createClient(url, key, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
}

// ────────────────────────────────────────────────────────────
// Organization
// ────────────────────────────────────────────────────────────

export type TestOrg = { id: string; slug: string }

export const createTestOrg = async (userId: string): Promise<TestOrg> => {
  const admin = getAdminClient()
  const slug = `e2e-org-${Date.now()}`

  const { data: org, error } = await admin
    .from('organizations')
    .insert({ name: `E2E Test Org ${Date.now()}`, slug, created_by: userId })
    .select('id')
    .single()

  if (error || !org) {
    throw new Error(`Failed to create test org: ${error?.message}`)
  }

  // Add owner membership
  const { error: memberError } = await admin.from('org_members').insert({
    org_id: org.id,
    user_id: userId,
    role: 'owner',
  })

  if (memberError) {
    throw new Error(`Failed to add org owner membership: ${memberError.message}`)
  }

  // Add org settings with defaults
  const { error: settingsError } = await admin.from('org_settings').insert({
    org_id: org.id,
  })

  if (settingsError) {
    throw new Error(`Failed to create org settings: ${settingsError.message}`)
  }

  return { id: org.id, slug }
}

// ────────────────────────────────────────────────────────────
// Project
// ────────────────────────────────────────────────────────────

export type TestProject = { id: string }

export const createTestProject = async (orgId: string, userId: string): Promise<TestProject> => {
  const admin = getAdminClient()

  const { data: project, error } = await admin
    .from('projects')
    .insert({
      org_id: orgId,
      title: `E2E Test Project ${Date.now()}`,
      description: 'Created by E2E test factory',
      owner_id: userId,
      current_step: 'identify',
      status: 'active',
    })
    .select('id')
    .single()

  if (error || !project) {
    throw new Error(`Failed to create test project: ${error?.message}`)
  }

  // Add project member (owner as lead)
  const { error: memberError } = await admin.from('project_members').insert({
    project_id: project.id,
    user_id: userId,
    role: 'lead',
  })

  if (memberError) {
    throw new Error(`Failed to add project member: ${memberError.message}`)
  }

  // Create the 6 PIPS project steps
  const pipsSteps = [
    'identify',
    'analyze',
    'generate',
    'select_plan',
    'implement',
    'evaluate',
  ] as const

  const steps = pipsSteps.map((step, i) => ({
    project_id: project.id,
    step,
    status: i === 0 ? 'in_progress' : 'not_started',
    started_at: i === 0 ? new Date().toISOString() : null,
  }))

  const { error: stepsError } = await admin.from('project_steps').insert(steps)

  if (stepsError) {
    throw new Error(`Failed to create project steps: ${stepsError.message}`)
  }

  return { id: project.id }
}

// ────────────────────────────────────────────────────────────
// Ticket
// ────────────────────────────────────────────────────────────

export type TestTicket = { id: string }

export const createTestTicket = async (
  orgId: string,
  userId: string,
  projectId?: string,
): Promise<TestTicket> => {
  const admin = getAdminClient()

  // Note: sequence_number is auto-generated by a DB trigger
  const { data: ticket, error } = await admin
    .from('tickets')
    .insert({
      org_id: orgId,
      title: `E2E Test Ticket ${Date.now()}`,
      description: 'Created by E2E test factory',
      type: 'task',
      status: 'backlog',
      priority: 'medium',
      reporter_id: userId,
      project_id: projectId ?? null,
    })
    .select('id')
    .single()

  if (error || !ticket) {
    throw new Error(`Failed to create test ticket: ${error?.message}`)
  }

  return { id: ticket.id }
}

// ────────────────────────────────────────────────────────────
// Team
// ────────────────────────────────────────────────────────────

export type TestTeam = { id: string }

export const createTestTeam = async (orgId: string, userId: string): Promise<TestTeam> => {
  const admin = getAdminClient()

  const { data: team, error } = await admin
    .from('teams')
    .insert({
      org_id: orgId,
      name: `E2E Test Team ${Date.now()}`,
      description: 'Created by E2E test factory',
      created_by: userId,
    })
    .select('id')
    .single()

  if (error || !team) {
    throw new Error(`Failed to create test team: ${error?.message}`)
  }

  // Add creator as team lead
  const { error: memberError } = await admin.from('team_members').insert({
    team_id: team.id,
    user_id: userId,
    role: 'lead',
  })

  if (memberError) {
    throw new Error(`Failed to add team member: ${memberError.message}`)
  }

  return { id: team.id }
}

// ────────────────────────────────────────────────────────────
// Cleanup
// ────────────────────────────────────────────────────────────

/**
 * Delete a test org and all its cascading data.
 * Use when cleanup needs to happen independently of user deletion
 * (e.g., when multiple orgs are created for the same user).
 */
export const cleanupTestOrg = async (orgId: string): Promise<void> => {
  const admin = getAdminClient()

  // Delete audit_log entries first (FK constraint blocks org deletion)
  await admin.from('audit_log').delete().eq('org_id', orgId)

  const { error } = await admin.from('organizations').delete().eq('id', orgId)

  if (error) {
    console.error(`Failed to cleanup test org ${orgId}: ${error.message}`)
  }
}
