#!/usr/bin/env bash
# Insert PIPS forms for 3 continuous improvement cycles
# Run from PIPS2.0 root

SUPABASE_URL="https://cmrribhjgfybbxhrsxqi.supabase.co"
SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcnJpYmhqZ2Z5YmJ4aHJzeHFpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjU0MjM4NCwiZXhwIjoyMDg4MTE4Mzg0fQ.ha76e3SZyOCVSDmSeoK8fwS1OBa7Uone-B4hF3-5vlc"
USER_ID="8787c5d6-aa93-458e-a77a-a731b34fb69f"
API="$SUPABASE_URL/rest/v1/project_forms"
HEADERS=(-H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -H "Prefer: return=representation")

insert_form() {
  local payload="$1"
  local result
  result=$(curl -s -X POST "$API" "${HEADERS[@]}" --data-raw "$payload")
  echo "$result" | python3 -c "import sys,json; d=json.load(sys.stdin); print('OK:', d[0]['form_type'] if isinstance(d,list) and d else 'ERROR:'+str(d))" 2>/dev/null || echo "raw: $result"
}

echo "=== CYCLE 1: TypeScript Strict Errors ==="

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000001","step":"identify","form_type":"problem_statement","title":"TS Strict Errors - Problem Statement","created_by":"'"$USER_ID"'","data":{"statement":"5 TypeScript compiler errors exist in test files (TS2532 and TS18048) preventing clean tsc --noEmit runs.","currentState":"5 errors: 1 in chat/actions.test.ts (TS2532), 4 in comment-actions.test.ts (TS18048).","desiredState":"Zero TypeScript errors. tsc --noEmit exits with code 0.","measurableGoal":"Reduce TypeScript error count from 5 to 0.","deadline":"2026-03-19"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000001","step":"analyze","form_type":"fishbone","title":"TS Strict Errors - Root Cause Analysis","created_by":"'"$USER_ID"'","data":{"problem":"TypeScript errors TS2532/TS18048 in test files","categories":{"People":["Test authors did not add null guards after array index access"],"Process":["No pre-commit tsc --noEmit hook on test files"],"Technology":["TypeScript strict marks array index access as possibly-undefined","Vitest mock.calls[] returns tuple elements with optional 2nd arg"],"Methods":["Direct property access on array[0] without undefined checks"]},"rootCause":"TypeScript strict mode marks array-indexed access as potentially undefined. Test code used direct access on mock.calls[0][1] and array[0] without guards, not caught by CI because typecheck step had not been enforced on test files."}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000001","step":"generate","form_type":"brainstorming","title":"TS Strict Errors - Solution Options","created_by":"'"$USER_ID"'","data":{"options":[{"id":1,"title":"Non-null assertion (!)","pros":["Minimal change","Explicit intent"],"cons":["Unsafe if test data changes"]},{"id":2,"title":"Type assertion cast","pros":["Preserves type info","Clean"],"cons":["Still needs outer ! for undefined array element"]},{"id":3,"title":"expect().toBeDefined() + !","pros":["Documents test assumptions","Safest"],"cons":["More lines of code"]},{"id":4,"title":"Disable strict for test files","pros":["Zero test file changes"],"cons":["Weakens type safety","Masks real bugs"]}]}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000001","step":"select","form_type":"implementation_plan","title":"TS Strict Errors - Implementation Plan","created_by":"'"$USER_ID"'","data":{"selectedOption":"Type cast + non-null assertion + expect().toBeDefined() guard","rationale":"Cast mock.calls[0]![1] as RequestInit to handle the optional 2nd arg. Add expect(firstNotif).toBeDefined() before using firstNotif! to document test assumptions explicitly.","steps":[{"order":1,"task":"Fix chat/actions.test.ts: extract fetchInit = mock.calls[0]![1] as RequestInit before JSON.parse"},{"order":2,"task":"Fix comment-actions.test.ts: add toBeDefined() assertion and use ! for property accesses"},{"order":3,"task":"Run npx tsc --noEmit to verify 0 errors"},{"order":4,"task":"Run pnpm test to verify all tests pass"},{"order":5,"task":"Commit with fix(quality) message"}],"estimatedEffort":"15 minutes","risks":"Low - test-only changes, no production impact"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000001","step":"evaluate","form_type":"evaluation","title":"TS Strict Errors - Evaluation","created_by":"'"$USER_ID"'","data":{"outcome":"All 5 TypeScript errors eliminated. tsc --noEmit now exits with code 0.","metricsAchieved":true,"lessonsLearned":["Array index access on mock.calls requires ! assertion or toBeDefined() guard in strict mode","Extracting mock call args into named vars before type-casting is cleaner than inline casts","expect(x).toBeDefined() before ! assertions documents test assumptions explicitly"],"nextActions":["Consider adding tsc --noEmit to pre-commit hook to prevent regressions"],"completedAt":"2026-03-19"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000001","step":"evaluate","form_type":"results_metrics","title":"TS Strict Errors - Results Metrics","created_by":"'"$USER_ID"'","data":{"metrics":[{"metric":"TypeScript errors","unit":"count","direction":"decrease","asIsValue":5,"targetValue":0,"achievedValue":0,"achieved":true}],"summary":"Reduced TypeScript strict mode errors from 5 to 0 in test files.","financialSavingsAnnual":0,"timeSavedWeeklyHours":0.5}}'

echo ""
echo "=== CYCLE 2: Unused Variable in reports/actions.ts ==="

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000002","step":"identify","form_type":"problem_statement","title":"Unused Variable - Problem Statement","created_by":"'"$USER_ID"'","data":{"statement":"reports/actions.ts declares actualHoursSaved but assigns 0 and never uses it, generating ESLint no-unused-vars warning and misleading future maintainers.","currentState":"Variable declared on line 302 with accumulator pattern but body sets it to 0 (placeholder comment). Value is never read downstream.","desiredState":"No unused variable warnings. Code accurately reflects what is and is not tracked.","measurableGoal":"Reduce ESLint no-unused-vars warnings by 1. Remove dead code.","deadline":"2026-03-19"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000002","step":"analyze","form_type":"fishbone","title":"Unused Variable - Root Cause Analysis","created_by":"'"$USER_ID"'","data":{"problem":"actualHoursSaved declared but never used in reports/actions.ts","categories":{"People":["Developer left placeholder variable when deferring hours tracking logic"],"Process":["No lint gate blocked the PR that introduced this"],"Technology":["ESLint no-unused-vars catches this but was previously set to warn not error"],"Code Quality":["Loop body sets actualHoursSaved += 0 with comment saying it is handled below, but the downstream code uses a different approach"]]},"rootCause":"Developer scaffolded actualHoursSaved accumulator intending to fill it in later, but completed the feature using a different variable pattern and left the dead code behind."}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000002","step":"generate","form_type":"brainstorming","title":"Unused Variable - Solution Options","created_by":"'"$USER_ID"'","data":{"options":[{"id":1,"title":"Remove variable entirely","description":"Delete let actualHoursSaved and the loop body that sets it to 0","pros":["Cleanest","Removes all dead code"],"cons":["If hours tracking is added later, developer must re-add"]},{"id":2,"title":"Rename with _ prefix","description":"Rename to _actualHoursSaved to match ignore pattern","pros":["Preserves intent","No logic change"],"cons":["Still dead code, just silenced"]},{"id":3,"title":"Actually implement hours tracking","description":"Fill in the accumulator with timeSavedWeeklyHours * 52","pros":["Adds real value"],"cons":["Scope creep for this fix cycle"]}]}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000002","step":"select","form_type":"implementation_plan","title":"Unused Variable - Implementation Plan","created_by":"'"$USER_ID"'","data":{"selectedOption":"Remove variable entirely","rationale":"The loop body already contains a comment explaining that hours are handled by a different variable downstream. The accumulator is dead code with no path to ever being read. Removing it is the cleanest and most honest change.","steps":[{"order":1,"task":"Delete let actualHoursSaved = 0 declaration on line 302"},{"order":2,"task":"Delete actualHoursSaved += 0 line and its comment inside the loop body"},{"order":3,"task":"Run eslint on reports/actions.ts to verify 0 warnings"},{"order":4,"task":"Run pnpm test to verify no behavior change"},{"order":5,"task":"Commit with fix(quality) message"}],"estimatedEffort":"5 minutes","risks":"Zero - dead code removal, no behavior change"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000002","step":"evaluate","form_type":"evaluation","title":"Unused Variable - Evaluation","created_by":"'"$USER_ID"'","data":{"outcome":"ESLint no-unused-vars warning eliminated from reports/actions.ts. No behavior change.","metricsAchieved":true,"lessonsLearned":["Placeholder accumulators with += 0 bodies are a code smell - should be removed or stubbed with _ prefix immediately","Lint warnings on unused vars should be treated as errors in CI to prevent accumulation"],"completedAt":"2026-03-19"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000002","step":"evaluate","form_type":"results_metrics","title":"Unused Variable - Results Metrics","created_by":"'"$USER_ID"'","data":{"metrics":[{"metric":"ESLint no-unused-vars warnings","unit":"count","direction":"decrease","asIsValue":1,"targetValue":0,"achievedValue":0,"achieved":true}],"summary":"Removed dead code accumulator variable from reports/actions.ts.","financialSavingsAnnual":0,"timeSavedWeeklyHours":0.1}}'

echo ""
echo "=== CYCLE 3: React Hook Lint Errors ==="

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000003","step":"identify","form_type":"problem_statement","title":"React Hook Lint Errors - Problem Statement","created_by":"'"$USER_ID"'","data":{"statement":"pnpm lint fails with 3 ESLint errors from react-hooks/purity (Date.now() in server components and hooks) and react-hooks/set-state-in-effect (setState in useEffect body), blocking the CI lint gate.","currentState":"3 lint errors: (1) projects/page.tsx calling Date.now() in async server component body, (2) use-relative-time.ts calling Date.now() in hook render path, (3) command-palette.tsx calling setRecentItems synchronously in useEffect.","desiredState":"pnpm lint passes with 0 errors. Lint gate is unblocked for CI.","measurableGoal":"Reduce ESLint errors from 4 to 0 (3 errors + 1 warning → 0).","deadline":"2026-03-19"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000003","step":"analyze","form_type":"fishbone","title":"React Hook Lint Errors - Root Cause Analysis","created_by":"'"$USER_ID"'","data":{"problem":"ESLint react-hooks/purity and react-hooks/set-state-in-effect errors","categories":{"Rules":["react-hooks/purity flags Date.now() as impure function even in async Server Components","react-hooks/set-state-in-effect flags any synchronous setState in effect body"],"Code":["use-relative-time.ts calls Date.now() directly in hook body during render - this is a genuine purity issue","projects/page.tsx is async Server Component - linter cannot distinguish from client hooks","command-palette.tsx reads localStorage on open via useEffect - idiomatic but flagged by strict rule"],"Process":["Lint was not run as a gate before these patterns were introduced"]},"rootCause":"Three distinct root causes: (1) use-relative-time.ts has a genuine render purity issue calling Date.now() that should be in state; (2) projects/page.tsx is safe but linter over-applies hook rules to async server functions; (3) command-palette.tsx uses idiomatic localStorage-on-mount pattern that strict rule flags."}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000003","step":"generate","form_type":"brainstorming","title":"React Hook Lint Errors - Solution Options","created_by":"'"$USER_ID"'","data":{"options":[{"id":1,"title":"Disable rule with eslint-disable-next-line for server component and effect","pros":["Minimal change","Preserves original intent"],"cons":["Suppresses rule rather than fixing root cause for server component"]},{"id":2,"title":"Fix use-relative-time.ts by moving Date.now() to state","description":"Use useState(() => Date.now()) so now is reactive and Date.now() is only called once per render cycle","pros":["Fixes root cause - genuinely better code","Removes impure function call from render path"],"cons":["Slightly more complex hook"]},{"id":3,"title":"Disable react-hooks rules globally for non-client files","pros":["Zero per-file changes"],"cons":["Hides real purity issues in actual hooks"]},{"id":4,"title":"Combination: fix use-relative-time properly + disable-next-line for server component and idiomatic effect","pros":["Correct fix for real issue, minimal suppression for false positives"],"cons":["Two different approaches in one PR"]}]}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000003","step":"select","form_type":"implementation_plan","title":"React Hook Lint Errors - Implementation Plan","created_by":"'"$USER_ID"'","data":{"selectedOption":"Fix use-relative-time.ts properly + eslint-disable comments for false positives","rationale":"use-relative-time.ts has a genuine render purity issue that deserves a proper fix (useState for now). The projects/page.tsx is an async Server Component where Date.now() is legitimately safe - use a targeted disable comment. The command-palette.tsx useEffect pattern is idiomatic and safe - use disable comment directly on the setRecentItems call.","steps":[{"order":1,"task":"Fix use-relative-time.ts: replace [,setTick] with [now,setNow] = useState(() => Date.now()), update interval to setNow(Date.now()), use now variable for diffMs calc"},{"order":2,"task":"Add eslint-disable-next-line react-hooks/purity comment before Date.now() in projects/page.tsx"},{"order":3,"task":"Add eslint-disable-next-line react-hooks/set-state-in-effect comment before setRecentItems() in command-palette.tsx"},{"order":4,"task":"Run eslint on affected files to verify 0 errors"},{"order":5,"task":"Run pnpm test to verify behavior unchanged"},{"order":6,"task":"Commit with fix(quality) message"}],"estimatedEffort":"20 minutes","risks":"Low - use-relative-time change is a refactor of how now is tracked (same value, now reactive)"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000003","step":"evaluate","form_type":"evaluation","title":"React Hook Lint Errors - Evaluation","created_by":"'"$USER_ID"'","data":{"outcome":"All 3 ESLint errors and 1 warning eliminated. pnpm lint passes with 0 issues.","metricsAchieved":true,"lessonsLearned":["Date.now() in custom hook render path is a real purity issue - use useState(() => Date.now()) to make it reactive","Async Server Components trigger react-hooks rules because linter does not distinguish function type - targeted eslint-disable is correct","Reading localStorage and setting state in useEffect is idiomatic and safe - eslint-disable with comment is appropriate documentation"],"completedAt":"2026-03-19"}}'

insert_form '{"project_id":"d6000000-0000-4000-8000-000000000003","step":"evaluate","form_type":"results_metrics","title":"React Hook Lint Errors - Results Metrics","created_by":"'"$USER_ID"'","data":{"metrics":[{"metric":"ESLint errors","unit":"count","direction":"decrease","asIsValue":3,"targetValue":0,"achievedValue":0,"achieved":true},{"metric":"ESLint warnings","unit":"count","direction":"decrease","asIsValue":1,"targetValue":0,"achievedValue":0,"achieved":true}],"summary":"Eliminated all 4 ESLint lint issues (3 errors + 1 warning) across 3 files.","financialSavingsAnnual":0,"timeSavedWeeklyHours":0.25}}'

echo ""
echo "All forms inserted."
